// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";

import {
  getNodeVersionError,
  isLegacyYarnLock,
  lintRepository,
} from "./npm-source-lint.ts";

const APPROVED_REGISTRY =
  "https://pkgs.dev.azure.com/ms/react-native/_packaging/react-native-public/npm/registry/";

function dependabot(...directories: string[]): string {
  return `version: 2
updates:
- package-ecosystem: npm
  directories:
${directories.map((directory) => `  - "${directory}"`).join("\n")}
  schedule:
    interval: weekly
`;
}

function validNpmFixture(): Record<string, string> {
  return {
    ".github/dependabot.yml": dependabot("/project"),
    "project/.npmrc": `registry=${APPROVED_REGISTRY}\nomit-lockfile-registry-resolved=true\n`,
    "project/package.json": JSON.stringify({
      name: "npm-fixture",
      version: "1.0.0",
      dependencies: { example: "^1.0.0" },
    }),
    "project/package-lock.json": JSON.stringify({
      name: "npm-fixture",
      version: "1.0.0",
      lockfileVersion: 3,
      requires: true,
      packages: {
        "": {
          name: "npm-fixture",
          version: "1.0.0",
          dependencies: { example: "^1.0.0" },
        },
        "node_modules/example": {
          version: "1.0.0",
          integrity: "sha512-example",
        },
      },
    }),
  };
}

function validYarnFixture(): Record<string, string> {
  return {
    ".github/dependabot.yml": dependabot("/project"),
    ".yarnrc.yml": `nodeLinker: node-modules\nnpmRegistryServer: "${APPROVED_REGISTRY}"\nyarnPath: .yarn/releases/yarn-4.13.0.cjs\n`,
    ".yarn/releases/yarn-4.13.0.cjs": "module.exports = {};\n",
    "project/package.json": JSON.stringify({
      name: "yarn-fixture",
      version: "1.0.0",
      packageManager: "yarn@4.13.0",
      dependencies: { example: "^1.0.0" },
    }),
    "project/yarn.lock": `__metadata:
  version: 8
  cacheKey: 10c0

"example@npm:^1.0.0":
  version: 1.0.0
  resolution: "example@npm:1.0.0"
  checksum: 10c0/example
  languageName: node
  linkType: hard
`,
  };
}

function createFixture(files: Record<string, string>): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "npm-source-lint-"));
  for (const [file, content] of Object.entries(files)) {
    const target = path.join(root, file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content);
  }
  execFileSync("git", ["init", "--quiet", root]);
  execFileSync("git", [
    "-C",
    root,
    "-c",
    "core.autocrlf=false",
    "add",
    "--all",
  ]);
  return root;
}

function removeFile(
  files: Record<string, string>,
  file: string,
): Record<string, string> {
  const result = { ...files };
  delete result[file];
  return result;
}

function assertValid(files: Record<string, string>): void {
  const root = createFixture(files);
  try {
    const result = lintRepository(root, { emit: false });
    assert.deepEqual(result.errors, []);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

function assertViolation(
  files: Record<string, string>,
  expected: RegExp,
): void {
  const root = createFixture(files);
  try {
    const result = lintRepository(root, { emit: false });
    assert.match(result.errors.join("\n"), expected);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

test("detects a Yarn 1 lockfile", () => {
  assert.equal(
    isLegacyYarnLock(
      "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n",
    ),
    true,
  );
});

test("accepts a Yarn 4 lockfile", () => {
  assert.equal(
    isLegacyYarnLock(
      '__metadata:\n  version: 8\n  cacheKey: 10c0\n\n"example@npm:^1.0.0":\n  version: 1.0.0\n',
    ),
    false,
  );
});

test("requires Node.js 24 or newer", () => {
  assert.match(getNodeVersionError("23.11.0") ?? "", /24 or newer/);
  assert.equal(getNodeVersionError("24.0.0"), undefined);
});

test("accepts npm locks with omitted registry URLs", () => {
  assertValid(validNpmFixture());
});

test("rejects an npmjs resolved URL", () => {
  const files = validNpmFixture();
  const lock = JSON.parse(files["project/package-lock.json"]);
  lock.packages["node_modules/example"].resolved =
    "https://registry.npmjs.org/example/-/example-1.0.0.tgz";
  files["project/package-lock.json"] = JSON.stringify(lock);
  assertViolation(files, /registry\.npmjs\.org/);
});

test("rejects another external HTTP tarball", () => {
  const files = validNpmFixture();
  const lock = JSON.parse(files["project/package-lock.json"]);
  lock.packages["node_modules/example"].resolved =
    "https://packages.example.com/example-1.0.0.tgz";
  files["project/package-lock.json"] = JSON.stringify(lock);
  assertViolation(files, /packages\.example\.com/);
});

test("rejects missing npm registry configuration", () => {
  assertViolation(
    removeFile(validNpmFixture(), "project/.npmrc"),
    /committed npm registry configuration is missing/,
  );
});

test("rejects missing omit-lockfile-registry-resolved", () => {
  const files = validNpmFixture();
  files["project/.npmrc"] = `registry=${APPROVED_REGISTRY}\n`;
  assertViolation(files, /omit-lockfile-registry-resolved/);
});

test("rejects an npm scoped registry override", () => {
  const files = validNpmFixture();
  files["project/.npmrc"] +=
    "@example:registry=https://packages.example.com/npm/\n";
  assertViolation(files, /@example:registry/);
});

test("rejects committed npm credentials", () => {
  const files = validNpmFixture();
  files["project/.npmrc"] += "//example.test/:_authToken=secret\n";
  assertViolation(files, /committed npm credentials are forbidden/);
});

test("accepts a configured Yarn 4 project", () => {
  assertValid(validYarnFixture());
});

test("rejects a legacy Yarn 1 lockfile", () => {
  const files = validYarnFixture();
  files["project/yarn.lock"] =
    "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n";
  assertViolation(files, /legacy Yarn 1 lockfile/);
});

test("rejects a Yarn public-registry URL", () => {
  const files = validYarnFixture();
  files["project/yarn.lock"] += `
"bad@npm:1.0.0":
  version: 1.0.0
  resolution: "https://registry.yarnpkg.com/bad/-/bad-1.0.0.tgz"
`;
  assertViolation(files, /registry\.yarnpkg\.com/);
});

test("rejects the wrong Yarn registry", () => {
  const files = validYarnFixture();
  files[".yarnrc.yml"] = files[".yarnrc.yml"].replace(
    APPROVED_REGISTRY,
    "https://registry.yarnpkg.com/",
  );
  assertViolation(files, /npmRegistryServer|registry\.yarnpkg\.com/);
});

test("rejects a Yarn scoped registry override", () => {
  const files = validYarnFixture();
  files[".yarnrc.yml"] +=
    `npmScopes:\n  example:\n    npmRegistryServer: "https://packages.example.com/npm/"\n`;
  assertViolation(files, /npmScopes\.example\.npmRegistryServer/);
});

test("rejects committed Yarn credentials", () => {
  const files = validYarnFixture();
  files[".yarnrc.yml"] += "npmAuthToken: secret\n";
  assertViolation(files, /committed Yarn credentials are forbidden/);
});

test("rejects a missing committed Yarn release", () => {
  assertViolation(
    removeFile(validYarnFixture(), ".yarn/releases/yarn-4.13.0.cjs"),
    /yarnPath target .* must be present in Git/,
  );
});

test("rejects an explicit remote package dependency", () => {
  const files = validNpmFixture();
  const manifest = JSON.parse(files["project/package.json"]);
  manifest.dependencies.example =
    "https://packages.example.com/example-1.0.0.tgz";
  files["project/package.json"] = JSON.stringify(manifest);
  assertViolation(files, /dependencies\.example/);
});

test("rejects a package dependency outside the repository", () => {
  const files = validNpmFixture();
  const manifest = JSON.parse(files["project/package.json"]);
  manifest.dependencies.example = "file:../../outside";
  files["project/package.json"] = JSON.stringify(manifest);
  assertViolation(files, /local path contained within the repository/);
});

test("rejects a package dependency at the repository parent", () => {
  const files = validNpmFixture();
  const manifest = JSON.parse(files["project/package.json"]);
  manifest.dependencies.example = "file:../..";
  files["project/package.json"] = JSON.stringify(manifest);
  assertViolation(files, /local path contained within the repository/);
});

test("rejects a wrapped remote Yarn locator", () => {
  const files = validYarnFixture();
  files["project/yarn.lock"] += `
"bad@git+ssh://git@example.test/repository.git":
  version: 1.0.0
  resolution: "bad@git+ssh://git@example.test/repository.git"
`;
  assertViolation(files, /git\+ssh/);
});

test("rejects an encoded remote Yarn locator", () => {
  const files = validYarnFixture();
  files["project/yarn.lock"] += `
"bad@patch:bad@https%3A%2F%2Fpackages.example.com%2Fbad.tgz#./bad.patch":
  version: 1.0.0
  resolution: "bad@patch:bad@https%3A%2F%2Fpackages.example.com%2Fbad.tgz#./bad.patch"
`;
  assertViolation(files, /packages\.example\.com/);
});

test("rejects an encoded git Yarn locator", () => {
  const files = validYarnFixture();
  files["project/yarn.lock"] += `
"bad@patch:bad@git%2Bssh%3A%2F%2Fgit%40example.test%2Frepository.git#optional!./bad.patch":
  version: 1.0.0
  resolution: "bad@patch:bad@git%2Bssh%3A%2F%2Fgit%40example.test%2Frepository.git#optional!./bad.patch"
`;
  assertViolation(files, /git%2Bssh/);
});

test("rejects missing Yarn metadata version", () => {
  const files = validYarnFixture();
  files["project/yarn.lock"] = "__metadata: {}\n";
  assertViolation(files, /metadata version 8 or newer/);
});

test("rejects an unowned install-capable package manifest", () => {
  const files = validNpmFixture();
  files["orphan/package.json"] = JSON.stringify({
    dependencies: { example: "^1.0.0" },
  });
  assertViolation(files, /orphan\/package\.json: install-capable/);
});

test("rejects a nonexistent Dependabot directory", () => {
  const files = validNpmFixture();
  files[".github/dependabot.yml"] = dependabot("/missing");
  assertViolation(files, /npm directory \/missing does not exist/);
});

test("rejects a duplicate Dependabot directory", () => {
  const files = validNpmFixture();
  files[".github/dependabot.yml"] = dependabot("/project", "/project");
  assertViolation(files, /required a unique directory/);
});

test("does not lint a tracked lockfile deleted in the working tree", () => {
  const root = createFixture(validNpmFixture());
  try {
    fs.rmSync(path.join(root, "project/package-lock.json"));
    const result = lintRepository(root, { emit: false });
    assert.doesNotMatch(result.errors.join("\n"), /unable to read file/);
    assert.match(result.errors.join("\n"), /found 0/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});
