version: 2
updates:
- package-ecosystem: npm
  directories:
  - "/.ado/scripts"
  - "/benchmarks/build-helpers/flow-bundler"
  - "/benchmarks/raytracer/original"
  - "/tools/fork-sync"
  - "/tools/hcdp"
  - "/tools/hermes-parser/js"
  - "/unittests/NodeApi/test"
  - "/utils/promise"
  - "/utils/scripts/hermes"
  groups:
    all-npm-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
    all-npm-security-updates:
      applies-to: security-updates
      patterns:
      - "*"
  schedule:
    interval: weekly
  labels:
  - dependencies
  versioning-strategy: lockfile-only
  commit-message:
    prefix: 📦
  open-pull-requests-limit: 5
  cooldown:
    default-days: 8
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    github-actions:
      patterns: ["*"]
  schedule:
    interval: "weekly"
  labels:
  - dependencies
  commit-message:
    prefix: 🎬
  cooldown:
    default-days: 8
