name: Hermes-Update-$(Date:yyMM.d)$(Rev:rrr)

pr: none
trigger: none
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight Facebook/Hermes ingestion
    branches:
      include:
        - main
# githubAuthToken

variables:
  - group: Hermes-Windows Secrets

jobs:
  - job: UpdateMetaMain
    timeoutInMinutes: 10
    pool: 
      vmImage: ubuntu-latest
    displayName: Update Hermes Branch to latest
    steps:
      - script: git remote add fb https://github.com/facebook/hermes
        displayName: Add facebook/hermes as report
      
      - script: git remote add authenticated https://rnbot:$(githubAuthToken)@github.com/microsoft/hermes-windows
        displayName: Add authenticated remote for updates

      - script: git fetch fb
        displayName: Fetch all latest facebook/hermes commits
      
      - script: |
          git reset fb/main --hard
          git log -1
        displayName: Get local state to match main commit in facebook/hermes

      - script: git push authenticated HEAD:meta_main --force
        displayName: Push latest commit to meta_main by force-pushing